export const MESSAGE_TYPES = {
  ELEMENT_ACTION: 'ELEMENT_ACTION',
  GET_VIDEOS_DATA: 'GET_VIDEOS_DATA',
  RESULT_VIDEOS_DATA: 'RESULT_VIDEOS_DATA',
  GET_TABS: 'GET_TABS',
  RESULT_TABS: 'RESULT_TABS',
  CHECK_ELEMENT_VIDEO_SELECTED: 'CHECK_ELEMENT_VIDEO_SELECTED',
  RESULT_CHECK_ELEMENT_VIDEO_SELECTED: 'RESULT_CHECK_ELEMENT_VIDEO_SELECTED',
  ADD_EVENTS_ELEMENT: 'ADD_EVENTS_ELEMENT',
  REMOVE_EVENTS_ELEMENTS: 'REMOVE_EVENTS_ELEMENTS',
  CHECK_CONNECTION: 'CHECK_CONNECTION',
  APP_INSTANCE_ALIVE: 'APP_INSTANCE_ALIVE',
  APP_INSTANCE_LOST_PRIMARY: 'APP_INSTANCE_LOST_PRIMARY',
  APP_INSTANCE_NOW_PRIMARY: 'APP_INSTANCE_NOW_PRIMARY',
};

export type MessageType = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES];

export interface MessageRequest<T = any> {
  cmd: MessageType;
  data?: T;
}
